-- Strada — contacts table, RLS, and ownership policies.
--
-- This file is the trust boundary. The Neon Data API is reachable by any signed-in
-- user without going through apps/api, so nothing in the Node layer can be relied on
-- for ownership or for input limits. Both are enforced here.
--
-- ORDERING NOTE: enable the Neon Data API BEFORE running this migration. Neon's
-- `ALTER DEFAULT PRIVILEGES ... GRANT ... TO authenticated` is installed when the Data
-- API is enabled; if this table is created first, those defaults never attach to it and
-- `authenticated` silently cannot touch the table.
--
-- AFTER running this: refresh the Data API schema cache (Neon Console -> Data API ->
-- Refresh schema cache). PostgREST returns PGRST205 "table not found" until you do.

create extension if not exists pgcrypto;

create table if not exists contacts (
  id         uuid        primary key default gen_random_uuid(),
  user_id    text        not null default (auth.user_id()),
  name       text        not null,
  company    text,
  role       text,
  met_where  text,
  notes      text,
  priority   text        not null default 'medium',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- Mirrors packages/shared/src/contact.ts. Change both in the same commit.
  constraint contacts_name_not_blank check (length(btrim(name)) > 0),
  constraint contacts_priority_valid check (priority in ('high', 'medium', 'low')),
  constraint contacts_name_len       check (length(name)      <= 200),
  constraint contacts_company_len    check (length(company)   <= 200),
  constraint contacts_role_len       check (length(role)      <= 200),
  constraint contacts_met_where_len  check (length(met_where) <= 200),
  constraint contacts_notes_len      check (length(notes)     <= 10000)
);

-- `id` is uuid, not `bigint generated by default as identity`, on purpose.
-- A client-suppliable integer primary key is a cross-user existence oracle: constraint
-- checks run outside RLS, so a duplicate-key error on INSERT {"id": N} reveals that row
-- N exists no matter who owns it, and probing N=1..10000 recovers the global row census.
-- A shared sequence additionally leaks every other user's insert volume.

create index if not exists contacts_user_id_idx on contacts (user_id);

-- Keep updated_at honest even for a direct Data API caller.
create or replace function set_updated_at() returns trigger
  language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists contacts_set_updated_at on contacts;
create trigger contacts_set_updated_at
  before update on contacts
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table contacts enable row level security;

-- FORCE matters: without it the table OWNER bypasses every policy below. That is the
-- role a migration script or a `psql $DATABASE_URL` session connects as, so without
-- FORCE an RLS test run over such a connection passes while proving nothing.
alter table contacts force row level security;

-- Four separate per-verb policies (not FOR ALL), each restricting access to rows whose
-- user_id matches the JWT `sub` claim that auth.user_id() returns.

drop policy if exists contacts_select_own on contacts;
create policy contacts_select_own on contacts
  for select to authenticated
  using (auth.user_id() = user_id);

drop policy if exists contacts_insert_own on contacts;
create policy contacts_insert_own on contacts
  for insert to authenticated
  with check (auth.user_id() = user_id);

-- USING gates the row as it exists; WITH CHECK gates the row as it would become.
-- Both are required: USING alone would let a user rewrite their own row's user_id and
-- hand it to someone else.
drop policy if exists contacts_update_own on contacts;
create policy contacts_update_own on contacts
  for update to authenticated
  using (auth.user_id() = user_id)
  with check (auth.user_id() = user_id);

drop policy if exists contacts_delete_own on contacts;
create policy contacts_delete_own on contacts
  for delete to authenticated
  using (auth.user_id() = user_id);

grant select, insert, update, delete on contacts to authenticated;

-- No grant to `anonymous` is issued, and none is revoked: CREATE TABLE grants nothing
-- to PUBLIC, Neon's anonymous role has no permissions by default, and all four policies
-- are scoped TO authenticated, so anonymous is default-denied three times over.
-- An explicit REVOKE would abort this migration if the role does not exist.
